name: Build Images
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Check out Repository
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          push: true
          build-args: |
            ENVOY_IMAGE=envoyproxy/envoy:v1.28.7
            CONSUL_IMAGE=hashicorp/consul:1.18
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name || github.repository_name }}:latest
          cache-to: type=inline
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name || github.repository_name }}:latest
